# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$os\
$username\
$directory\
$git_branch\
$line_break\
$character\
"""

right_format = """
$git_status\
$git_metrics\
$docker_context\
$c\
$cpp\
$cmake\
$dotnet\
$golang\
$java\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$conda\
$cmd_duration[  ](none)\
"""
        

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[✘ ](bold red)"
vimcmd_symbol = "[: ](bold fg:yellow)"

[directory]
read_only = " 󰌾"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "


[git_branch]
symbol = " "
#style = "fg:lavender bg:base"
format = ' \([$symbol$branch]($style)\)'

[git_status]
format = " [$untracked$staged$modified$renamed$conflicted$ahead_behind]($style)"
# options available for format
staged     = "[+](green)"
modified   = "[!](yellow)"
renamed    = "[»](blue)"
deleted    = "[-](red)"
untracked  = "[?](red)"
stashed    = "[≡](lavender)"
conflicted = "[✖](red bold)"

ahead      = "[⇡${count}](teal)"
behind     = "[⇣${count}](peach)"
diverged   = "[⇕⇡${ahead_count}⇣${behind_count}](mauve)"

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
format = '([+$added]($added_style)) ([-$deleted]($deleted_style))'

[cmd_duration]
min_time = 500
format = " [took $duration]($style)"

[time]
disabled = false
time_format = "%H:%M"
format = " [ $time]($style)"

[username]
disabled = false
show_always = true
style_user = "bold yellow"
style_root = "bold red"
format = '\[[$user]($style)\]'


[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[container]
symbol = " "


[docker_context]
symbol = " "

[dotnet]
symbol = " "

[fossil_branch]
symbol = " "


[git_commit]
tag_symbol = '  '

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[kubernetes]
symbol = "󱃾 "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[status]
symbol = " "

[sudo]
symbol = " "


[os]
format = "[$symbol]($style)"
disabled = false

[os.symbols]
Arch = " "
CachyOS = " "
Linux = " "
Ubuntu = " "
